{% set name = "yt-dlp" %}
{% set version = "2025.8.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d1846bbb7edbcd2a0d4a2d76c7a2124868de9ea3b3959a8cb8219e3f7cb5c335

build:
  number: 0
  noarch: python
  entry_points:
    - yt-dlp = yt_dlp:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
  run_constrained:
    - brotli
    - brotlicffi
    - certifi
    - mutagen
    - pycryptodomex
    - requests <3,>=2.32.2
    - urllib3 >=2.0.2,<3
    - websockets >=13.0

test:
  imports:
    - yt_dlp
    - yt_dlp.compat
  commands:
    - pip check
    - yt-dlp --help
    - yt-dlp --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yt-dlp/yt-dlp
  summary: A youtube-dl fork with additional features and patches
  dev_url: https://github.com/yt-dlp/yt-dlp
  license: Unlicense
  license_file: LICENSE
  description: |
    yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project.
  doc_url: https://github.com/yt-dlp/yt-dlp/wiki

extra:
  recipe-maintainers:
    - HeavyTony2
