{% set name = "yt-dlp" %}
{% set version = "2024.12.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 743dbe081ea871be3f5ff083e2cd95da866dea773fc70ae6b109838cfbf72ac4

build:
  number: 1
  noarch: python
  entry_points:
    - yt-dlp = yt_dlp:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - setuptools >=71.0.2
  run:
    - python >={{ python_min }}
  run_constrained:
    - brotli
    - brotlicffi
    - certifi
    - mutagen
    - pycryptodomex
    - requests <3,>=2.32.2
    - urllib3 >=1.26.17,<3
    - websockets >=13.0

test:
  imports:
    - yt_dlp
    - yt_dlp.compat
  commands:
    - pip check
    - yt-dlp --help
    - yt-dlp --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yt-dlp/yt-dlp
  summary: A youtube-dl fork with additional features and patches
  dev_url: https://github.com/yt-dlp/yt-dlp
  license: Unlicense
  license_file: LICENSE
  description: |
    yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project

extra:
  recipe-maintainers:
    - HeavyTony2
