schema_version: 1

context:
  name: yt-dlp
  version: "2025.12.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b773c81bb6b71cb2c111cfb859f453c7a71cf2ef44eff234ff155877184c3e4f

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - yt-dlp = yt_dlp:main

requirements:
  host:
    - python ${{ python_min }}*
    - hatchling >=1.27.0
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - yt-dlp-ejs ==0.3.2 #technically is an optional dependancies but as part of the "default" installation
  run_constraints:
    - brotli
    - brotlicffi
    - certifi
    - mutagen
    - pycryptodomex
    - requests <3,>=2.32.2
    - urllib3 >=2.0.2,<3
    - websockets >=13.0
    - autopep8 >=2.0,<3.dev0
    - ruff >=0.13.0,<0.14.dev0

tests:
  - python:
      imports:
        - yt_dlp
        - yt_dlp.compat
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - yt-dlp --help
      - yt-dlp --version

about:
  summary: A youtube-dl fork with additional features and patches
  license: Unlicense
  license_file: LICENSE
  description: |
    yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project.
  homepage: https://github.com/yt-dlp/yt-dlp
  repository: https://github.com/yt-dlp/yt-dlp
  documentation: https://github.com/yt-dlp/yt-dlp/wiki

extra:
  recipe-maintainers:
    - HeavyTony2
